version: '2'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ivr
  server:
    image: stikks/ivr
    ports:
      - "8981:80"
      - "443:443"
    volumes:
      - .:/opt/IVR
  rabbit:
    image: rabbitmq
  redis:
    image: redis
  elasticsearch:
    image: elasticsearch
  freepbx:
    image: stikks/freepbx
    ports:
      - "8982:80"
  app:
    image: stikks/node-app
    ports:
      - "4043:4043"
  worker:
    image: stikks/worker-app